# Generated by Django 3.2.25 on 2025-10-17 23:21

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_permission', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the style')),
                ('length', models.CharField(choices=[('SHORT', 'Short'), ('MEDIUM', 'Medium'), ('LONG', 'Long')], default='SHORT', max_length=10)),
                ('maintenance', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('texture', models.CharField(choices=[('STRAIGHT', 'Straight'), ('WAVY', 'Wavy'), ('CURLY', 'Curly'), ('COILY', 'Coily')], default='STRAIGHT', max_length=10)),
                ('thickness', models.CharField(choices=[('FINE', 'Fine'), ('MEDIUM', 'Medium'), ('THICK', 'Thick')], default='FINE', max_length=10)),
                ('stylist_name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='Unique name to describe the style', max_length=350)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text="Add any additional tags like 'blonde' for hair color", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('image_alt', models.CharField(help_text='Provide alt text for the image', max_length=350)),
                ('type', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], default='BEFORE', max_length=10)),
                ('view', models.CharField(choices=[('SIDE', 'Side'), ('FRONT', 'Front'), ('BACK', 'Back')], default='FRONT', max_length=10)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_image', to='styles.style')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
