# Generated by Django 3.2.25 on 2025-10-19 18:40

from django.db import migrations, models
import styles.models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/', validators=[styles.models.validate_image_file_extension, styles.models.validate_image_file_size]),
        ),
    ]
