# Generated by Django 3.2.25 on 2025-10-22 00:45

from django.db import migrations, models
import styles.models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='styles/', validators=[styles.models.validate_image_file_extension, styles.models.validate_image_file_size]),
        ),
    ]
