# Generated by Django 3.2.25 on 2025-11-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='face_shape',
            field=models.CharField(blank=True, choices=[('ROUND', 'Round'), ('SQUARE', 'Square'), ('OVAL', 'Oval'), ('HEART', 'Heart'), ('DIAMOND', 'Diamond'), ('OBLONG', 'Oblong'), ('TRIANGLE', 'Triangle')], default='HEART', max_length=10),
        ),
        migrations.AddField(
            model_name='style',
            name='gender',
            field=models.CharField(choices=[('WOMAN', 'Woman'), ('MAN', 'Man'), ('OTHER', 'Other')], default='WOMAN', max_length=10),
        ),
    ]
